// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yanovych_back.Repos;

namespace yanovych_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221216125829_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("yanovych_back.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Mark")
                        .HasColumnType("float");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2022-10-01",
                            Mark = 7.0,
                            Priority = 3,
                            Status = "Evaluated",
                            Title = "Lab1"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2022-10-10",
                            Mark = 0.0,
                            Priority = 2,
                            Status = "Submitted",
                            Title = "Lab2"
                        });
                });

            modelBuilder.Entity("yanovych_back.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Attendance")
                        .HasColumnType("float");

                    b.Property<double>("ExamMark")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("StudentList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attendance = 16.0,
                            ExamMark = 48.0
                        },
                        new
                        {
                            Id = 2,
                            Attendance = 12.0,
                            ExamMark = 42.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
